version: "3"
services:
  selenium-chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    shm_size: '2gb'

  test-runner:
    build: .
    depends_on:
      - selenium-chrome
    environment:
      - SELENIUM_REMOTE_URL=http://selenium-chrome:4444/wd/hub
